name: Update BNR
on:
  schedule:
    - cron: '0 21 * * *'  # Ruleaza la ora 24:00 (00:00) ora Romaniei
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Fetch BNR
        run: python update_bnr.py
      - name: Commit JSON
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add curs.json
          git commit -m "Update curs BNR" || echo "No changes"
          git push
